version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/node

hooks:
  AfterInstall:
    - location: /deploy/hooks/after-install.sh
      runas: root
  ApplicationStart:
    - location: /deploy/hooks/application-start.sh
      runas: root
  ApplicationStop:
    - location: /deploy/hooks/application-stop.sh
      runas: root
  ValidateService:
    - location: /deploy/hooks/validate-service.sh
      runas: root
